services:
    moon.pmimport.controller.main:
        class: moon\pmimport\controller\main_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    moon.pmimport.listener:
        class: moon\pmimport\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
