services:
  mebird.pmimport.listener:
    class: mebird\pmimport\event\main_listener
    arguments:
    tags:
      - { name: event.listener }
  # TODO: update all of these services w/table names
  mebird.vldr.import_service:
    class: mebird\vldr\service\location_service
    arguments:
      - '@user'
      - '@dbal.conn'
      - '@text_formatter.s9e.parser'
