services:
  bevansm.isos.listener:
    class: bevansm\isos\event\main_listener
    arguments:
      - '@language'
      - '@controller.helper'
      - '@template'
      - '%core.php_ext%'
      - '@dbal.conn'
    tags:
      - { name: event.listener }
