imports:
  - { resource: parameters.yml }

services:
  mebird.pmimport.controller.ucp:
    class: mebird\pmimport\controller\ucp_controller
    arguments:
      - '@dbal.conn'
      - '@language'
      - '@request'
      - '@template'
      - '@user'
  mebird.pmimport.listener:
    class: mebird\pmimport\event\main_listener
    arguments:
      - '@language'
      - '@controller.helper'
      - '@template'
      - '%core.php_ext%'
    tags:
      - { name: event.listener }
