services:
  bevansm.pmimport.listener:
    class: bevansm\pmimport\event\main_listener
    arguments:
    tags:
      - { name: event.listener }
  bevansm.pmimport.import_service:
    class: bevansm\pmimport\service\import_service
    arguments:
      - '@user'
      - '@dbal.conn'
      - '@text_formatter.s9e.parser'
